[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.76",
    "langgraph>=0.6.7",
    "requests>=2.32.5",
]
